const CLOSED_COLOR = "#185527";
const EXPIRED_COLOR = "#939598";
const WITHDRAW_COLOR = "#666465";
const ACTIVE_COLOR = "#28b24b";
const UNDER_CONTRACT_COLOR = "#b3daad";
const CONRTOLED_COLOR = "#B3DAAD";
const PROGRESS_BAR_ORANGE_COLOR = "#FBB040";
const GREY_COLOR = "#BFBCBC";

export {
  CLOSED_COLOR,
  EXPIRED_COLOR,
  WITHDRAW_COLOR,
  ACTIVE_COLOR,
  UNDER_CONTRACT_COLOR,
  CONRTOLED_COLOR,
  PROGRESS_BAR_ORANGE_COLOR,
  GREY_COLOR
}