const CLOSED_COLOR = "#215528";
const WITHDRAW_COLOR = "#666465";
const CONRTOLED_COLOR = "#B3DAAD";
const PROGRESS_BAR_ORANGE_COLOR = "#FBB040";
const GREY_COLOR = "#BFBCBC";

export {
  CLOSED_COLOR,
  WITHDRAW_COLOR,
  CONRTOLED_COLOR,
  PROGRESS_BAR_ORANGE_COLOR,
  GREY_COLOR
}